spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  custom:
    message: "Hello from Service A! vijay"
